baseurl = "/"

# datocms:start
title = "Conflux"
defaultcontentlanguage = "en"
defaultcontentlang = "en"
defaultcontentlanguageinsubdir = true
disableAliases = true
# datocms:end


[languages]
  [languages.nl]
    contentDir = 'content/nl'
    languageName = 'Nederlands'
    title = 'Nederlands'
    weight = 2
  [languages.en]
    contentDir = 'content/en'
    languageName = 'English'
    title = 'English'
    weight = 1
    
[params]
  env = "development"