baseurl = "/"

# datocms:start
title = "Conflux"
defaultContentLanguage = "en"
defaultContentLang = "en"
defaultContenLanguageInSubdir = true
disableAliases = true
# datocms:end

[languages]
  [languages.nl]
    contentDir = 'content/nl'
    languageName = 'Nederlands'
    title = 'Nederlands'
    weight = 2
  [languages.en]
    contentDir = 'content/en'
    languageName = 'English'
    title = 'English'
    weight = 1

[params]
  env = "production"